CREATE TABLE IF NOT EXISTS list (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CREATE USER IF NOT EXISTS admin WITH PASSWORD admin;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
    GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO admin;
);